# 서버 포트 설정
server.port=8000

# 데이터베이스 설정
spring.datasource.url=jdbc:h2:mem:bbumas
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 콘솔 활성화
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Thymeleaf 설정
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# 파일 업로드 관련 설정
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Python 스크립트 경로 설정
python.image.script.path=src/main/resources/python/analyze_image.py
python.script.path=src/main/resources/python/analyze_video.py
python.command=python
python.timeout=120

# YOLO 모델 경로 설정
yolo.model.path=src/main/resources/models/yolov8n.pt

# 정적 리소스 설정
spring.web.resources.static-locations=file:./uploads/,classpath:/static/
spring.mvc.static-path-pattern=/**

python.env.path=/path/to/python/venv